### ISSUE TITLE
Theme screenshot is not updating

### ISSUE THREAD

**Issue by stpaultim** [backdrop-ops/backdropcms.org#566]
I created a new theme using an old screenshot of Basis. I changed the screenshot and cut a new release, but the old screenshot is still showing up on BackdropCMS.org.

Here is the new screenshot:
https://github.com/backdrop-contrib/tatsu/blob/1.x-1.x/screenshot.png

Here is project page with old screenshot:
https://backdropcms.org/project/tatsu

Is there something I need to do to force the update?

**Comment by stpaultim** [comment]
I asked about this during a dev meeting and learned that the screenshot is uploaded initially, but is not updated later. Work is being done which might effect this and this should be fixed in the future. In the meantime, someone with edit access on BackdropCMS.org can update the project node. I was able to do this for myself.

**Comment by indigoxela** [comment]
This is still an issue unfortunately... Any plans to fix this?
